### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by legoeugen** [Nikorasu/LiveWhisper#5]
When I try to use it, it gives me this error

Traceback (most recent call last):
  File "E:\PyCharm\LiveWhisper\livewhisper.py", line 2, in <module>
    import whisper, os
  File "E:\Anaconda\envs\LiveWhisper\lib\site-packages\whisper.py", line 69, in <module>
    libc = ctypes.CDLL(libc_name)
  File "E:\Anaconda\envs\LiveWhisper\lib\ctypes\__init__.py", line 364, in __init__
    if '/' in name or '\\' in name:
TypeError: argument of type 'NoneType' is not iterable

**Comment by Nikorasu** [comment]
Odd, I'm really not sure why Whisper's files are giving you an error upon import.
Tho I'm not sure if/how Anaconda might impact things..
